embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"animacion_enemigo_fuego\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/Assets/sprites.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"enemigo\"\n"
  "mask: \"default\"\n"
  "mask: \"jugador\"\n"
  "mask: \"proyectil\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -16.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"hitbox_enemigo_fuego\"\n"
  "  }\n"
  "  data: 55.971203\n"
  "  data: 40.017715\n"
  "  data: 9.36\n"
  "}\n"
  ""
}
