embedded_components {
  id: "Sprite Oro"
  type: "sprite"
  data: "default_animation: \"animacion_moneda_oro\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/Assets/sprites.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"enemigo\"\n"
  "mask: \"default\"\n"
  "mask: \"jugador\"\n"
  "mask: \"jugador_alcanzado\"\n"
  "mask: \"proyectil\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "    id: \"hitbox_item_moneda\"\n"
  "  }\n"
  "  data: 31.80894\n"
  "}\n"
  ""
}
embedded_components {
  id: "Sprite Plata"
  type: "sprite"
  data: "default_animation: \"animacion_moneda_plata\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/Assets/sprites.atlas\"\n"
  "}\n"
  ""
}
