function init(self)
	-- Obtiene el botón de iniciar juego
	self.boton_iniciar = gui.get_node("BotonJugar")
	-- Obtiene el botón de salir del juego
	self.boton_salir = gui.get_node("BotonSalir")
	-- Pide al sistema que este script pueda escuchar los clics del mouse/teclado
	msg.post(".", "acquire_input_focus")
end

function on_input(self, id_accion, accion)
	-- Si la acción es un clic izquierdo ("LeftClick" debe estar en tu input_binding) y se presionó
	if id_accion == hash("touch") and accion.pressed then
		-- Si el clic ocurrió sobre el botón de Iniciar
		if gui.pick_node(self.boton_iniciar, accion.x, accion.y) then
			-- Envía un mensaje al controlador principal para cambiar de escena a "level"
			-- Nota: He traducido "change_scene" a "cambiar_escena". 
			-- Asegúrate de que el script main:/SceneParent entienda este mensaje en español.
			msg.post("main:/GestorEscena", "cambiar_escena", { escena = "level" })
		end
		-- Si el clic ocurrió sobre el botón de Salir
		if gui.pick_node(self.boton_salir, accion.x, accion.y) then
			-- Cierra la aplicación
			os.exit()
		end
	end
end